server:
  port: 8081
  error:
    include-message: always
spring:
  application:
    name: ms-rooms
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: fkubis
    password: fkubis
    driver-class-name: org.postgresql.Driver
